### PR TITLE
Import tibble for printing

### PR DESCRIPTION
**Pull request by MikeJohnPage**
**Issue**
When printing an adam dataset to the console (e.g., by running `pharmasverseadam::adlb`), tibble formatting is dropped unless you load the tibble (or tidyverse) package because tibble is not imported in the package. This PR fixes this by importing tibble ensuring that the adam datasets print correctly, even without loading tibble/tidyverse first.

**Checklist**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build pharmaverseadam site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new datasets occur on the "[Reference](https://pharmaverse.github.io/pharmaverseadam/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by manciniedoardo** [comment]
Hi @MikeJohnPage - thanks for the PR! We can definitely look to update this. For completeness could you please:

- Make a corresponding issue for this PR as we track all updates through issues
- Add a line in the NEWS.md for this update, referencing that issue.

After that is done please let me know and I will be happy to review and approve.

**Comment by MikeJohnPage** [comment]
Opened issue #95 

Where would you like me to place the item in `NEWS.md`. Do you need me to bump the version number of the package?

**Comment by manciniedoardo** [comment]
> Opened issue #95
> 
> Where would you like me to place the item in `NEWS.md`. Do you need me to bump the version number of the package?

We have a workflow for that so it can be placed under `pharmaverseadam (development version)` like we did for 1.1.0:

image

**Comment by manciniedoardo** [comment]
> Okay, done 👍

Thanks - unfortunately not quite what I was meaning sorry, I might've been unclear.  I think you are missing the development version section? See the [version in main right now](https://github.com/pharmaverse/pharmaverseadam/blob/main/NEWS.md) for comparison. We should add a new "developer notes" section under the development version, with this update. You can merge main into your branch to get the latest NEWS.md as it updated after you started working on this. Thanks!

Also pls fix failing spelling check by adding "tibble" to `inst/WORDLIST`.

**Comment by MikeJohnPage** [comment]
I've made the changes you requested 👍

**Review by manciniedoardo — APPROVED** [review]
Thanks @MikeJohnPage LGTM 😄

**Pull request merged**
